name: Compile Translations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Babel
      run: |
        python -m pip install --upgrade pip
        pip install Babel

    - name: Compile .po files to .mo files
      run: |
        pybabel compile -d translations

    - name: Commit compiled .mo files
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add translations/**/*.mo
        git commit -m "Automated compilation of .mo files"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
